[build.environment]
  NETLIFY_USE_PNPM = "true"
  NODE_VERSION = "18"
[build]
  command = "OUTPUT=netlify astro build"
  functions = "netlify/functions"
  publish = "dist/"
[[edge_functions]]
  path = "/"
  function = "geolocation"
