name: 🐞 Bug report (When using)
description: Report an issue or possible bug when using `chatgpt-demo`
labels: ['pending triage', 'use']
body:
  - type: markdown
    attributes:
      value: |
        ### Before submitting...
        Thanks for taking the time to fill out this bug report! Please confirm the following points before submitting:

        ✅ I have checked the bug was not already reported by searching on GitHub under issues.
        ✅ Use English to ask questions. This allows more people to search and participate in the issue.
  - type: input
    id: os
    attributes:
      label: What operating system are you using?
      placeholder: Mac, Windows, Linux
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: What browser are you using?
      placeholder: Chrome, Firefox, Safari
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: prompt
    attributes:
      label: What prompt did you enter?
      description: If the issue is related to the prompt you entered, please fill in this field.
  - type: textarea
    id: console-logs
    attributes:
      label: Console Logs
      description: Please check your browser and fill in the error message if it exists.
  - type: checkboxes
    id: will-pr
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request for this issue.
          required: false